#!/bin/bash

SCRIPT_COMMON_FILE=/usr/local/rak/shell_script/rak_common.sh

source $SCRIPT_COMMON_FILE

RAK_MODEL=`do_get_gw_model`
GW_VERSION=`do_get_gw_version`
GW_ID=`do_get_gw_id`
LORA_SPI=`do_get_lora_spi`

if [ "${RAK_MODEL}" = "RAK2247" ] || [ "${RAK_MODEL}" = "RAK833" ]; then
    if [ "${LORA_SPI}" = "1" ]; then
        GW_MODEL_STR="${RAK_MODEL} for SPI"
    else
        GW_MODEL_STR="${RAK_MODEL} for USB"
    fi
else
    GW_MODEL_STR=$RAK_MODEL
fi

echo "Gateway ID:$GW_ID"
echo "RAKWireless gateway $GW_MODEL_STR version $GW_VERSION"
