#!/bin/bash

GATEWAY_EUI_NIC="wlan0"

GATEWAY_EUI=$(ip link show $GATEWAY_EUI_NIC | awk '/ether/ {print $2}' | awk -F\: '{print $5$6}')
GATEWAY_EUI=${GATEWAY_EUI^^}

sed -i "26c SSID=Rakwireless_$GATEWAY_EUI" /usr/local/rak/ap/create_ap.conf
sed -i "s/^.*ap_ssid.*$/\\t\\t\"ap_ssid\":\"Rakwireless_$GATEWAY_EUI\",/" /usr/local/rak/gateway-config-info.json
