#!/bin/bash

# Try to get gateway ID from MAC address
# First try eth0, if that does not exist, try wlan0 (for RPi Zero)
GATEWAY_EUI_NIC="eth0"
if [[ `grep "$GATEWAY_EUI_NIC" /proc/net/dev` == "" ]]; then
    GATEWAY_EUI_NIC="wlan0"
fi

if [[ `grep "$GATEWAY_EUI_NIC" /proc/net/dev` == "" ]]; then
    GATEWAY_EUI_NIC="usb0"
fi

if [[ `grep "$GATEWAY_EUI_NIC" /proc/net/dev` == "" ]]; then
    echo "ERROR: No network interface found. Cannot set gateway ID."
    exit 1
fi

GATEWAY_EUI=$(ip link show $GATEWAY_EUI_NIC | awk '/ether/ {print $2}' | awk -F\: '{print $1$2$3"FFFE"$4$5$6}')
GATEWAY_EUI=${GATEWAY_EUI^^} 

while [ true=true  ]
do
    ret=`ps -ef|grep chirpstack_as|grep -v grep|wc -l`
    if [ "$ret" = "0" ]; then 
        echo "while as 001"
    else
        str_1=`sudo -u postgres psql chirpstack_as -c "update gateway set mac='\x$GATEWAY_EUI';"`
        break
    fi
    sleep 1
done

while [ true=true  ]
do
    ret=`ps -ef|grep chirpstack_ns|grep -v grep|wc -l`
    if [ "$ret" = "0" ]; then
        echo "while ns 001"
    else
        str_2=`sudo -u postgres psql chirpstack_ns -c "update gateway set gateway_id='\x$GATEWAY_EUI';"`
        break
    fi
    sleep 1
done

