#!/bin/bash
SCRIPT_COMMON_FILE=/usr/local/rak/shell_script/rak_common.sh

source $SCRIPT_COMMON_FILE
# Try to get gateway ID from MAC address
# First try eth0, if that does not exist, try wlan0 (for RPi Zero)
INSTALL_CHIRPSTACK=`do_get_gw_install_chirpstack`
GATEWAY_EUI=`do_get_gw_id`

if [ "$INSTALL_CHIRPSTACK" = "0" ]; then
    exit
fi

while [ true=true  ]
do
    ret=`ps -ef|grep chirpstack_as|grep -v grep|wc -l`
    if [ "$ret" = "0" ]; then 
        echo "while as 001"
    else
        str_1=`sudo -u postgres psql chirpstack_as -c "update gateway set mac='\x$GATEWAY_EUI';"`
        break
    fi
    sleep 1
done

while [ true=true  ]
do
    ret=`ps -ef|grep chirpstack_ns|grep -v grep|wc -l`
    if [ "$ret" = "0" ]; then
        echo "while ns 001"
    else
        str_2=`sudo -u postgres psql chirpstack_ns -c "update gateway set gateway_id='\x$GATEWAY_EUI';"`
        break
    fi
    sleep 1
done

